# Generated by Django 3.2.25 on 2024-12-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField()),
                ('status', models.CharField(max_length=500)),
                ('btime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='doctorTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('doctoredu', models.CharField(max_length=200)),
                ('docexp', models.CharField(max_length=200)),
                ('prevhosp', models.CharField(max_length=100)),
                ('docphone', models.BigIntegerField()),
                ('docmail', models.EmailField(max_length=254)),
                ('doccertificate', models.FileField(upload_to='')),
                ('docimage', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='loginTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pin', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('phoneno', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintbl')),
            ],
        ),
        migrations.CreateModel(
            name='suggestionTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('sugdate', models.DateField()),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertbl')),
            ],
        ),
        migrations.CreateModel(
            name='scheduleTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField()),
                ('ftime', models.TimeField()),
                ('ttime', models.TimeField()),
                ('DOCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctortbl')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=300)),
                ('BOOK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bookingtbl')),
            ],
        ),
        migrations.CreateModel(
            name='feedbackTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=300)),
                ('fdate', models.DateField()),
                ('DOC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctortbl')),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertbl')),
            ],
        ),
        migrations.AddField(
            model_name='doctortbl',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.logintbl'),
        ),
        migrations.CreateModel(
            name='complaintTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('cdate', models.DateField()),
                ('USERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertbl')),
            ],
        ),
        migrations.AddField(
            model_name='bookingtbl',
            name='SCHEDULE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.scheduletbl'),
        ),
        migrations.AddField(
            model_name='bookingtbl',
            name='USERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertbl'),
        ),
    ]
