# Generated by Django 3.2.25 on 2025-01-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='findings',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.FileField(upload_to=''),
        ),
    ]
