# Generated by Django 3.2.25 on 2025-01-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250102_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=2008),
            preserve_default=False,
        ),
    ]
