# Generated by Django 3.2.25 on 2025-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_prescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttbl',
            name='reply',
            field=models.CharField(default='pending', max_length=500),
        ),
    ]
