
from django.urls import path
from myapp import views

urlpatterns = [
path('',views.login),
path('login_post',views.login_post),
path('admin_add_doctor',views.admin_add_doctor),
path('admin_adddoc_post',views.admin_adddoc_post),
path('admin_complaint',views.admin_complaint),
path('admin_doctorlist',views.admin_doctorlist),
path('admin_homehosp',views.admin_homehosp),
path('admin_managesugg',views.admin_managesugg),
path('admin_replysend',views.admin_replysend),
path('admin_updatedsched/<int:id>',views.admin_updatedsched),
path('admin_viewbooking',views.admin_viewbooking),
path('admin_viewfeed',views.admin_viewfeed),
path('admin_viewscheddoc/<int:id>',views.admin_viewscheddoc),
path('adminunblockDoctor/<int:id>',views.adminunblockDoctor),
path('admin_addschedule',views.admin_addschedule),
path('admin_viewsheddoc',views.admin_viewsheddoc),
path('admin_addsched_post',views.admin_addsched_post),
path('adminRejectDoctor/<int:id>',views.adminRejectDoctor),
path('admindoctorsearch',views.admindoctorsearch),
path('admin_schedsearch',views.admin_schedsearch),
path('admin_sending',views.admin_sending),
path('admin_logout',views.admin_logout),
path('admin_updatesave',views.admin_updatesave),
path('admin_rejectbooking/<int:id>',views.admin_rejectbooking),
path('admin_approvebooking/<int:id>',views.admin_approvebooking),
path('dochome',views.dochome),
path('prescription_load/<id>',views.prescription_load),
path('addpresc_post',views.addpresc_post),
path('updatedoc',views.updatedoc),
path('updatepresc/<id>',views.updatepresc),
path('updatesched',views.updatesched),
path('viewbooking',views.viewbooking),
path('viewdetails',views.viewdetails),
path('doclogout',views.doclogout),
path('viewProfile',views.viewProfile),
path('updatedetails',views.updatedetails),
path('addpresc',views.addpresc),
path('updatepresc_post',views.updatepresc_post),


path('android_login',views.android_login),
path('user_reg',views.user_reg),
path('user_view_doctor',views.user_view_doctor),
path('user_view_doctor_schedule',views.user_view_doctor_schedule),
path('sendfeedback',views.sendfeedback),
path('/sendcomplaint',views.sendcomplaint),
path('/viewreply',views.viewreply),
path('search_doctor',views.search_doctor),
path('user_book_doctor',views.user_book_doctor),
path('user_view_booking',views.user_view_booking),
path('image_upload',views.image_upload),
]
